### PR TITLE
Fix/198 silent token refresh

### LINKED ISSUE #198: Token does not refresh silently
- Make sure the access token refreshes silently in the background and the user is kept logged in throughout his shift.
- Change access token duration from 5 to 15 mins.

### PR DESCRIPTION
**Pull request by Guy-Ghis**
- Modified the error handling to skip 401 errors entirely, allowing the auth interceptor to handle them. Generic 401 errors mean "token expired" and should trigger a refresh, not a logout. Only explicit `SESSION_REVOKED` codes should log users out.
- Corrected the session object structure to use accessToken consistently.
- Implemented Event-Based State Synchronization between the Interceptor and AuthContext React State. When the interceptor refreshes a token, the AuthContext React state is immediately updated, keeping the UI in sync without requiring a page reload.
- Enhanced Auth Interceptor Logic and Session Persistence Across Page Reloads
- Increased access token duration from 1 minute to 15 minutes

### CODE REVIEW

**Review by Ayonta-2 — APPROVED** [review]

File: frontend/src/contexts/AuthContext.tsx [hunk 1]
```diff
@@ -114,6 +114,25 @@ export function AuthProvider({ children }: { children: ReactNode }) {
   // Assign the global logout function to the instance logout so the interceptor can call it
   useEffect(() => {
     globalLogout = () => logout(true);
+
+    // Listen for token refresh events from the interceptor
+    const handleTokenRefreshed = (event: Event) => {
+      const customEvent = event as CustomEvent<{ accessToken: string; session: AuthResponse }>;
+      const { accessToken, session: updatedSession } = customEvent.detail;
```
Comment (Ayonta-2) [inline frontend/src/contexts/AuthContext.tsx]: Just remove the unused variable here

**Review by Arielpetit — APPROVED** [review]
